import Head from 'next/head'
import Image from 'next/image'
import Main from '../components/Main'

export default function Home() {
  return (
    <>

      <Head>
        <title>Bored af</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/bored2.svg" />
      </Head>

      <div className='relative min-h-full'>
      <h1 className='animate-moving-line '>Nav</h1>

      </div>

    </>
  )
}
