import Head from 'next/head'
import Image from 'next/image'
import Landing from '../components/Landing'
import Main from '../components/Main'
import TaskSearch from '../components/TaskSearch'

export default function Home() {
  const gifs=["https://media1.giphy.com/media/xUPGcm3irC17U1FgMo/giphy.gif?cid=790b7611257c65491ba775059655b53cbd3a8e4c3b18dc0a&rid=giphy.gif&ct=g","https://i.imgur.com/ac6aspn.gif" ]
  return (
    <>
{/* 
      <Head>
        <title>Bored af</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/bored2.svg" />
      </Head> */}
<div className='min-h-full max-h-[100vh] min-w-full gap-2 grid grid-cols-5 overflow-hidden'>
  <div className='col-span-3 border'>
    <Landing/>
  </div>
  <div className='col-span-2 border'>

    <Image src={gifs[0]} alt="emoji" width={700} height={500} className="animate-fade-in-down" />
    </div>


</div>
     

    </>
  )
}
